fix: 修复终端可用

diff --git a/tools/rebuild-node-modules b/tools/rebuild-node-modules
--- a/tools/rebuild-node-modules
+++ b/tools/rebuild-node-modules
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+# 参数：
+# 1 ---- NW版本
+# 
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
   DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
@@ -7,12 +9,27 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
   [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
-
+NW_VERSION=$1
 package_dir="$DIR/../package.nw"
 
-export PATH=$DIR/../node/bin:$PATH
+if [ -z $NW_VERSION ]; then
+  echo "NW 版本未指定！"
+  exit 1
+fi
+echo "目录: $DIR"
+echo "NW VERSION: $NW_VERSION"
 
-node --version
+export PATH="$DIR/../node/bin:$PATH"
+PY_VERSION=`python -V 2>&1|awk '{print $2}'|awk -F '.' '{print $1}'`
+if [ $PY_VERSION != 2 ]; then
+  hash python2 2>/dev/null || { echo >&2 "I require python2 but it's not installed.  Aborting."; exit 1; }
+  ln -s "$( which python2 )" "$DIR/../node/bin/python"
+fi
+
+hash nw-gyp 2>/dev/null || {
+  echo "=======请安装nw-gyp======="
+  exit 1
+}
 
 rm -fr "${package_dir}/node_modules/vscode-windows-ca-certs" # the module is only available in windows
 rm -fr "${package_dir}/node_modules/vscode-windows-registry" # the module is only available in windows
@@ -21,8 +38,7 @@ rm -fr "${package_dir}/node_modules/windows-process-tree" # the module is only a
 
 rm -fr "${package_dir}/node_modules/vscode-ripgrep/bin" # redownload bin on linux
 
-rm -fr "${package_dir}/node_modules/node-pty/build/Release/conpty.node" # the native module is not available in windows
-rm -fr "${package_dir}/node_modules/node-pty/build/Release/conpty_console_list.node" # the native module is not available in windows
+rm -fr "${package_dir}/node_modules/node-pty" "${package_dir}/node_modules/node-pty-node" # the native module is not available in windows
 
 (cd "${package_dir}/node_modules" && find -name *.pdb | xargs -I{} rm -r {}) # remove pdb debugging file
 
@@ -30,14 +46,14 @@ rm -fr "${package_dir}/node_modules_tmp" # remove previous hacking tmp
 mkdir -p "${package_dir}/node_modules_tmp"
 cp -fr "${package_dir}/node_modules" "${package_dir}/node_modules_tmp/node_modules" 
 
+rm -fr "${package_dir}/node_modules_tmp/node_modules/node-pty"
 rm -fr "${package_dir}/node_modules_tmp/node_modules/node-pty-node"
+rm -fr "${package_dir}/node_modules_tmp/node_modules/native-watchdog"
 rm -fr "${package_dir}/node_modules_tmp/node_modules/oniguruma-node"
 rm -fr "${package_dir}/node_modules_tmp/node_modules/spdlog"
 rm -fr "${package_dir}/node_modules_tmp/node_modules/spdlog-node"
 
-# npm install @vscode/ripgrep --registry=https://registry.npm.taobao.org
-# npm install nodegit --registry=https://registry.npm.taobao.org --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/v0.27.0/
-(cd "${package_dir}/node_modules_tmp" && npm install \
+(npm install \
     extract-file-icon \
     native-keymap \
     node-pty \
@@ -48,18 +64,28 @@ rm -fr "${package_dir}/node_modules_tmp/node_modules/spdlog-node"
     vscode-oniguruma \
     vscode-ripgrep \
     nodegit \
+    --prefix="${package_dir}/node_modules_tmp" \
+    --registry=https://registry.npm.taobao.org \
     --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/v0.27.0/) # reinstall modules
 
+# rebuild
+echo "nw-gyp version: $( nw-gyp --version )"
+cd "$package_dir/node_modules_tmp/node_modules/node-pty" && nw-gyp rebuild --arch=x64 "--target=$NW_VERSION"
 (cp -fr "${package_dir}/node_modules_tmp/node_modules/node-pty" "${package_dir}/node_modules_tmp/node_modules/node-pty-node")
+rm -rf "${package_dir}/node_modules/node-pty" "${package_dir}/node_modules/node-pty-node"
+cp -fr "${package_dir}/node_modules_tmp/node_modules/node-pty" "${package_dir}/node_modules"
+(cp -fr "${package_dir}/node_modules/node-pty" "${package_dir}/node_modules/node-pty-node")
+
+cd "$package_dir/node_modules_tmp/node_modules/native-watchdog" && nw-gyp rebuild --arch=x64 "--target=$NW_VERSION"
+rm -rf "${package_dir}/node_modules/native-watchdog" && cp -fr "${package_dir}/node_modules_tmp/node_modules/native-watchdog" "${package_dir}/node_modules"
+
 (cp -fr "${package_dir}/node_modules_tmp/node_modules/oniguruma" "${package_dir}/node_modules_tmp/node_modules/oniguruma-node")
 (cp -fr "${package_dir}/node_modules_tmp/node_modules/spdlog" "${package_dir}/node_modules_tmp/node_modules/spdlog-node")
 
-(cd "${package_dir}/node_modules_tmp/node_modules" && find -name "*.node" | xargs -I{} cp -r {} ${package_dir}/node_modules/{})
+(cd "${package_dir}/node_modules_tmp/node_modules" && find -name "*.node" | xargs -I{} /bin/cp -rf {} ${package_dir}/node_modules/{})
 
 mkdir -p "${package_dir}/node_modules/vscode-ripgrep/bin"
 cp -fr "${package_dir}/node_modules_tmp/node_modules/vscode-ripgrep/bin/rg" "${package_dir}/node_modules/vscode-ripgrep/bin/rg"
-
-rm -rf "${package_dir}/node_modules/native-watchdog" && cp -fr "${package_dir}/node_modules_tmp/node_modules/native-watchdog" "${package_dir}/node_modules"
 
 rm -rf "${package_dir}/node_modules_tmp"
 
